language: java

jdk:
- openjdk8

before_cache:
- rm -rf $HOME/.m2/repository/**/*-SNAPSHOT

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"

script:
- "cd quarkus.jdt.ext && ./mvnw clean verify && cd .."
- "cd quarkus.ls.ext/com.redhat.quarkus.ls && ./mvnw clean verify"

notifications:
  email: true